# Generated by Django 6.1.1 on 2026-09-15 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_comment_follow_like'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam o publicidad'), ('harassment', 'Acoso o insultos'), ('hate', 'Discurso de odio'), ('sexual', 'Contenido sexual'), ('violence', 'Violencia'), ('fake', 'Cuenta falsa o suplantación'), ('other', 'Otro')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Pendiente'), ('resolved', 'Resuelto'), ('dismissed', 'Descartado')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='moderation__school__a0c397_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('reporter', 'post'), name='unique_report_post'), models.UniqueConstraint(condition=models.Q(('reported_user__isnull', False)), fields=('reporter', 'reported_user'), name='unique_report_user'), models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('reported_user__isnull', True)), models.Q(('post__isnull', True), ('reported_user__isnull', False)), _connector='OR'), name='report_tiene_un_objetivo')],
            },
        ),
    ]
