# Generated by Django 6.1.1 on 2026-09-23 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
        ("posts", "0002_comment_follow_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="communities.community",
            ),
        ),
    ]
